# Generated by Django 5.1 on 2024-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergen', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('condition', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('address', models.TextField()),
                ('blood_type', models.CharField(max_length=3)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('language_preference', models.CharField(max_length=100)),
                ('allergies', models.ManyToManyField(to='TapSOS.allergy')),
                ('medical_conditions', models.ManyToManyField(to='TapSOS.medicalcondition')),
            ],
        ),
    ]
